# Generated by Django 5.2 on 2025-04-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_event', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titres', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
