# Generated by Django 5.2 on 2025-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bflc', '0002_activites_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites',
            name='date_aj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='albums',
            name='date_aj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_aj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='date_aj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
