# Generated by Django 5.2 on 2025-04-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bflc', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_aj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
